# Generated by Django 5.1.3 on 2024-11-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_studentdb_age_studentdb_gender_studentdb_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdb',
            name='MOBILE',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
